/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.DAOs.PlaylistDAO;
import Model.Playlist;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Gamer
 */
public class TelaPlaylists extends javax.swing.JFrame {

    private int idUsuario;

    /**
     * Creates new form TelaPlaylists
     */
    public TelaPlaylists(int idUsuario) {
        initComponents();
        this.idUsuario = idUsuario;
        carregarPlaylists();
    }

    private void carregarPlaylists() { //Lista as playlists do usuario
        PlaylistDAO dao = new PlaylistDAO();
        List<Playlist> playlists = dao.listarPorUsuario(idUsuario);

        DefaultListModel<String> model = new DefaultListModel<>();
        for (Playlist p : playlists) {
            model.addElement(p.getNome());
        }
        listaPlaylists.setModel(model);
    }

    public JButton getBtnCriar() {
        return btnCriar;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public JButton getBtnExcluir() {
        return btnExcluir;
    }

    public JButton getBtnVerMusicas() {
        return btnVerMusicas;
    }

    public JButton getBtnVoltar() {
        return btnVoltar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JList<String> getListaPlaylists() {
        return listaPlaylists;
    }


    public void setBtnCriar(JButton btnCriar) {
        this.btnCriar = btnCriar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public void setBtnExcluir(JButton btnExcluir) {
        this.btnExcluir = btnExcluir;
    }


    public void setBtnVerMusicas(JButton btnVerMusicas) {
        this.btnVerMusicas = btnVerMusicas;
    }

    public void setBtnVoltar(JButton btnVoltar) {
        this.btnVoltar = btnVoltar;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public void setListaPlaylists(JList<String> listaPlaylists) {
        this.listaPlaylists = listaPlaylists;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaPlaylists = new javax.swing.JList<>();
        btnVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        btnVerMusicas = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciar Playlists");
        setResizable(false);

        listaPlaylists.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaPlaylists);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("SPOTIFEI");

        btnExcluir.setText("Excluir playlist");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnVerMusicas.setText("Ver músicas");
        btnVerMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMusicasActionPerformed(evt);
            }
        });

        btnEditar.setText("Renomear playlist");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCriar.setText("Criar playlist");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCriar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerMusicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        //Cria uma nova playlist
        String nome = javax.swing.JOptionPane.showInputDialog(this, "Digite o nome da nova playlist:");

        if (nome != null && !nome.trim().isEmpty()) {
            Playlist novaPlaylist = new Playlist();
            novaPlaylist.setNome(nome.trim());
            novaPlaylist.setIdUsuario(idUsuario); // usa o ID do usuário logado

            PlaylistDAO dao = new PlaylistDAO();
            boolean sucesso = dao.criarPlaylist(novaPlaylist);

            if (sucesso) {
                javax.swing.JOptionPane.showMessageDialog(this, "Playlist criada com sucesso!");
                carregarPlaylists(); // Atualiza a lista
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao criar a playlist.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nome da playlist não pode ser vazio.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //Edita o nome da playlist
        int indiceSelecionado = listaPlaylists.getSelectedIndex();
        if (indiceSelecionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma playlist para renomear.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        PlaylistDAO dao = new PlaylistDAO();
        List<Playlist> playlists = dao.listarPorUsuario(idUsuario);
        Playlist playlistSelecionada = playlists.get(indiceSelecionado);

        String novoNome = javax.swing.JOptionPane.showInputDialog(this, "Digite o novo nome para a playlist:", playlistSelecionada.getNome());

        if (novoNome != null && !novoNome.trim().isEmpty()) {
            playlistSelecionada.setNome(novoNome.trim());

            boolean sucesso = dao.renomearPlaylist(playlistSelecionada);

            if (sucesso) {
                javax.swing.JOptionPane.showMessageDialog(this, "Playlist renomeada com sucesso!");
                carregarPlaylists();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao renomear a playlist.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Nome da playlist não pode ser vazio.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //Remove a playlit selecionada
        int selectedIndex = listaPlaylists.getSelectedIndex();
        if (selectedIndex == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma playlist para excluir.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir a playlist selecionada?", "Confirmar exclusão", javax.swing.JOptionPane.YES_NO_OPTION);
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            PlaylistDAO dao = new PlaylistDAO();
            Playlist playlistSelecionada = dao.listarPorUsuario(idUsuario).get(selectedIndex); // pega a playlist completa pelo índice

            boolean sucesso = dao.excluirPlaylist(playlistSelecionada.getId());
            if (sucesso) {
                javax.swing.JOptionPane.showMessageDialog(this, "Playlist excluída com sucesso!");
                carregarPlaylists();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao excluir a playlist.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnVerMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMusicasActionPerformed
        //Leva a tela de manipulação das musicas da playlist selecionada
        int indiceSelecionado = listaPlaylists.getSelectedIndex();
        if (indiceSelecionado == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma playlist para ver as músicas.", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        PlaylistDAO dao = new PlaylistDAO();
        List<Playlist> playlists = dao.listarPorUsuario(idUsuario);
        int idPlaylistSelecionada = playlists.get(indiceSelecionado).getId();

        TelaMusicasPlaylist telaMusicas = new TelaMusicasPlaylist(idPlaylistSelecionada, idUsuario);
        telaMusicas.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVerMusicasActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        new TelaPrincipal(Model.Sessao.getUsuario()).setVisible(true); // Abre o menu principal
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVerMusicas;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaPlaylists;
    // End of variables declaration//GEN-END:variables
}
