/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Usuario;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Model.Sessao;
import Model.Usuario;

/**
 *
 * @author uniflelias
 */

public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Construtor padrão (caso queira abrir sem login)
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * Construtor que recebe o usuário e exibe uma saudação no título
     */
    public TelaPrincipal(Usuario user) {
        initComponents();
        Model.Sessao.setUsuario(user); // Salvamento do usuário para ações futuras
        // Saudação via título da janela
        setTitle("Spotifei – Bem-vindo, " + user.getNome() + "!");
        JOptionPane.showMessageDialog(this,
            "Olá, " + user.getNome() + "!",
            "Bem-vindo",
            JOptionPane.INFORMATION_MESSAGE);
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnBuscarMusicas = new javax.swing.JButton();
        btnPlaylists = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("SPOTIFEI");

        btnBuscarMusicas.setText("Pesquisa de músicas");
        btnBuscarMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMusicasActionPerformed(evt);
            }
        });

        btnPlaylists.setText("Playlists");
        btnPlaylists.setMaximumSize(new java.awt.Dimension(72, 23));
        btnPlaylists.setMinimumSize(new java.awt.Dimension(72, 23));
        btnPlaylists.setPreferredSize(new java.awt.Dimension(72, 23));
        btnPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaylistsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPlaylists, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBuscarMusicas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarMusicas)
                .addGap(18, 18, 18)
                .addComponent(btnPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMusicasActionPerformed
        Usuario usuarioLogado = Model.Sessao.getUsuario();
    if (usuarioLogado != null) {
        int idUsuario = usuarioLogado.getId();
        new TelaBuscarMusica(idUsuario).setVisible(true);
        this.dispose();
    } else {
        // Se não tiver usuário logado, mostrar mensagem de erro (opcional)
        JOptionPane.showMessageDialog(this, "Usuário não está logado!", "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBuscarMusicasActionPerformed

    private void btnPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaylistsActionPerformed
        Usuario usuarioLogado = Model.Sessao.getUsuario();
        if (usuarioLogado != null) {
            int idUsuario = usuarioLogado.getId();
            new TelaPlaylists(idUsuario).setVisible(true);
            this.dispose();
        } else {
           JOptionPane.showMessageDialog(this, "Usuário não está logado!", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnPlaylistsActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMusicas;
    private javax.swing.JButton btnPlaylists;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
