/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import Model.Usuario;

/**
 * Tela principal do sistema Spotifei.
 * Exibe opções para pesquisa de músicas, gerenciamento de playlists e visualização do histórico.
 * Exibe uma saudação ao usuário logado.
 * 
 * @author Leonardo Bezzi Elias
 */

public class TelaPrincipal extends javax.swing.JFrame {
    /**
     * Controle para mostrar a mensagem de boas-vindas apenas uma vez.
     */
    private static boolean mensagemMostrada = false;
    
    /**
     * Construtor padrão da tela principal.
     * Usado quando a tela é aberta sem um usuário logado.
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * Construtor da tela principal que recebe o usuário logado.
     * Atualiza o título da janela com a saudação ao usuário.
     * Mostra uma mensagem de boas-vindas (uma única vez).
     * 
     * @param user Usuário logado que acessou o sistema.
     */
    public TelaPrincipal(Usuario user) {
        initComponents();
        Model.Sessao.setUsuario(user); // Salvamento do usuário para ações futuras
        setTitle("Spotifei – Bem-vindo, " + user.getNome() + "!"); // Saudação via título da janela
        
        if (!mensagemMostrada){
        JOptionPane.showMessageDialog(this,
            "Olá, " + user.getNome() + "!",
            "Bem-vindo",
            JOptionPane.INFORMATION_MESSAGE);
        mensagemMostrada = true;    
        }
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnBuscarMusicas = new javax.swing.JButton();
        btnPlaylists = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("SPOTIFEI");

        btnBuscarMusicas.setText("Pesquisa de músicas");
        btnBuscarMusicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMusicasActionPerformed(evt);
            }
        });

        btnPlaylists.setText("Playlists");
        btnPlaylists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaylistsActionPerformed(evt);
            }
        });

        btnHistorico.setText("Histórico");
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnBuscarMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaylists, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMusicas, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Ação executada ao clicar no botão "Pesquisa de músicas".
     * Abre a tela de busca de músicas para o usuário logado.
     * Exibe mensagem de erro se não houver usuário logado.
     * 
     * @param evt Evento do clique no botão.
     */
    private void btnBuscarMusicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMusicasActionPerformed
        //Leva a tela de busca
        Usuario usuarioLogado = Model.Sessao.getUsuario();
        if (usuarioLogado != null) {
            int idUsuario = usuarioLogado.getId();
            new TelaBuscarMusica(idUsuario).setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Usuário não está logado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarMusicasActionPerformed
    /**
     * Ação executada ao clicar no botão "Playlists".
     * Abre a tela de gerenciamento de playlists para o usuário logado.
     * Exibe mensagem de erro se não houver usuário logado.
     * 
     * @param evt Evento do clique no botão.
     */
    private void btnPlaylistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaylistsActionPerformed
        //Leva a tela das playlists
        Usuario usuarioLogado = Model.Sessao.getUsuario();
        if (usuarioLogado != null) {
            int idUsuario = usuarioLogado.getId();
            new TelaPlaylists(idUsuario).setVisible(true);
            this.dispose();
        } else {
           JOptionPane.showMessageDialog(this, "Usuário não está logado!", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_btnPlaylistsActionPerformed
    /**
     * Ação executada ao clicar no botão "Histórico".
     * Abre a tela de histórico de atividades para o usuário logado.
     * Exibe mensagem de erro se não houver usuário logado.
     * 
     * @param evt Evento do clique no botão.
     */
    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        //Leva a pagina de historico
        Usuario usuarioLogado = Model.Sessao.getUsuario();
        if (usuarioLogado != null) {
            int idUsuario = usuarioLogado.getId();
            new TelaHistorico(idUsuario).setVisible(true);
            this.dispose();  
        } else {
            JOptionPane.showMessageDialog(this, "Usuário não está logado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnHistoricoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarMusicas;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnPlaylists;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
